# GCP Cloud Build [ CI / CD ]
steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'pre-build'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo ENV Values                                   \
        && echo ----------------------------------------- \
        && echo Build Location : $LOCATION                \
        && echo Build ID       : $BUILD_ID                \
        && echo Project ID     : $PROJECT_ID              \
        && echo TRIGGER_NAME   : $TRIGGER_NAME            \
        && echo COMMIT_ID      : $COMMIT_SHA              \
        && echo _NODE_ENV     : $_NODE_ENV              \
        && echo INSTANCE       : $_INSTANCE_NAME          \
        && echo -----------------------------------------

  - name: 'gcr.io/$PROJECT_ID/docker-compose'
    id: 'docker-compose up'
    args: ['up']

  - name: 'docker/compose:1.29.0'
    id: 'docker-compose build'
    args:
      - -f
      - docker-compose.$_NODE_ENV.yaml
      - build

  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'cloud-builders gcloud push'
    args:
      - push
      - $_IMAGE_NAME

  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'deploy'
    args: 
      - 'run'
      - 'deploy'
      - '${_INSTANCE_NAME}'
      - '--image=${_IMAGE_NAME}'
      - '--region=${_INSTANCE_ZONE}'
      - '--platform=managed'

substitutions:
  _IMAGE_NAME: gcr.io/${PROJECT_ID}/redis-standard-client:${_NODE_ENV}-${BUILD_ID}
  _INSTANCE_NAME: _INSTANCE_NAME
  _INSTANCE_ZONE: _INSTANCE_ZONE
  _NODE_ENV: _NODE_ENV
  
options:
  logging: CLOUD_LOGGING_ONLY
  dynamic_substitutions: true

images:
  - 'gcr.io/$PROJECT_ID/redis-standard-client:$_NODE_ENV-$BUILD_ID'

tags: ['cloud-builders-community']