# GCP Cloud Build [ CI / CD ]
steps:
  - name: docker/compose:1.29.0
    args:
      - -f
      - docker-compose.$_MODE.yaml
      - build
  
  - name: docker/compose:1.29.0
    args:
      - -f
      - docker-compose.$_MODE.yaml
      - push

options:
  logging: CLOUD_LOGGING_ONLY