# GCP Cloud Build [ CI / CD ]
steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'pre-build'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo ENV Values                                   \
        && echo ----------------------------------------- \
        && echo Build Location : $LOCATION                \
        && echo Build ID       : $BUILD_ID                \
        && echo Project ID     : $PROJECT_ID              \
        && echo TRIGGER_NAME   : $TRIGGER_NAME            \
        && echo COMMIT_ID      : $COMMIT_SHA              \
        && echo ----------------------------------------- \
        && echo _INSTANCE_NAME : $_INSTANCE_NAME          \
        && echo _INSTANCE_ZONE : $_INSTANCE_ZONE          \
        && echo _NODE_ENV      : $_NODE_ENV               \
        && echo _IMAGE_NAME    : $_IMAGE_NAME             \
        && echo _IMAGE_TAG     : $_IMAGE_TAG              \
        && echo _IMAGE_URL     : $_IMAGE_URL              \
        && echo ----------------------------------------- \

  - name: 'docker/compose:1.29.0'
    id: 'docker-compose build'
    args:
      - -f
      - docker-compose.$_NODE_ENV.yaml
      - build

  - name: 'gcr.io/cloud-builders/docker'
    id: 'tag-image'
    args:
      - tag
      - $_IMAGE_NAME:$_NODE_TAG
      - ${_IMAGE_URL}

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-image'
    args:
      - push
      - ${_IMAGE_URL}

  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'deploy'
    args: 
      - 'run'
      - 'deploy'
      - '${_INSTANCE_NAME}'
      - '--image=${_IMAGE_URL}'
      - '--region=${_INSTANCE_ZONE}'
      - '--platform=managed'

substitutions:
  _IMAGE_NAME: redis-standard-client
  _IMAGE_TAG: $_NODE_ENV-$BUILD_ID
  _IMAGE_URL: gcr.io/${PROJECT_ID}/${_IMAGE_NAME}:${_IMAGE_TAG}
  _INSTANCE_NAME: _INSTANCE_NAME
  _INSTANCE_ZONE: _INSTANCE_ZONE
  _NODE_ENV: _NODE_ENV
  
options:
  logging: CLOUD_LOGGING_ONLY
  dynamic_substitutions: true

images:
  - 'gcr.io/$PROJECT_ID/${_IMAGE_TAG}:$_NODE_ENV-$BUILD_ID'
