version: "3"

services:
  redis-standard:
    container_name: redis-standard
    build:
      context: .
      dockerfile: ./docker/redis/standard/Dockerfile
    ports:
      - "7349:7349"
    networks:
      - redis-server
    restart: unless-stopped

  node-redis-standard-client:
    container_name: node-redis-client
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    environment:
      NODE_MODE: production
    ports:
      - "4200:4200"
    depends_on:
      - redis-standard
    networks:
      - redis-server
    restart: unless-stopped

networks:
  redis-server:
