openapi: 3.0.3
info:
  title: Mapsea Standard Redis Reverse Proxy Server
  description: |-
    # Mapsea Standard Redis Reverse Proxy Server
    **Endpoint:**  /api/</br>
    **Swagger:**  /api-docs</br>
    **Platform:** Node.Js<br>
    **FrameWork:** Express<br>
    **DevLanguage:** typescript<br>
    **Developer:** 최민석(devbyul-mapsea)

    <h2>Descritpion</h2> Redis 관리하기 위해 작성한 OpenApi Reverse Porxy 서버입니다.<br>
    
    <h2>추가 작업 필요 사항</h2>
    - 서버 접근에 대한 WhiteList 작성
  contact:
    email: devbyul@mapseacorp.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11

servers:
  - url: http://127.0.0.1:4200
  - url: http://dev.api.redis-standard.dev-sea.com

tags:
  - name: status
    description: Server Status 확인용 API 입니다.
  - name: standard-openapi
    description: standard redis 를 사용 중인 openapi 서버입니다.

paths:
  $ref: './path.yaml'

security:
  - authorization: []

components:
  securitySchemes:
    authorization:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    ##########################################################################################
    ##################                    Http Status 4XX                   ##################
    ##########################################################################################
    # 인증 실패한 경우 
    Authentication:
      type: object
      properties:
        code:
          type: string
          example: AUTHENTICATION_FAILED
        statusCode:
          type: number
          example: 401
        message:
          type: string
          example: Authentication failed
    # 권한 문제 발생한 경우 
    AuthForbidden:
      type: object
      properties:
        code:
          type: string
          example: AUTH_FORBIDDEN
        statusCode:
          type: number
          example: 403
        message:
          type: string
          example: You do not have permission to access that path.
    # JWT 문제 발생한 경우 
    JsonWebTokenError__400:
      type: object
      properties:
        code:
          type: string
          example: JSON_WEB_TOKEN_ERROR
        statusCode:
          type: number
          example: 400
        message_1:
          type: string
          example: jwt must be provided
        message_2:
          type: string
          example: jwt signature is required
        message_3:
          type: string
          example: invalid signature
    JsonWebTokenError__401:
      type: object
      properties:
        code:
          type: string
          example: JSON_WEB_TOKEN_ERROR
        statusCode:
          type: number
          example: 401
        message_1:
          type: string
          example: not found authorization header
        message_2:
          type: string
          example: jwt malformed
        message_3:
          type: string
          example: jwt audience invalid
        message_4:
          type: string
          example: jwt issuer invalid
        message_5:
          type: string
          example: jwt id invalid
        message_6:
          type: string
          example: jwt subject invalid
        message_7:
          type: string
          example: jwt algorithm invalid          
    # 중복 계정을 회원가입 할 경우
    DuplicationError:
      type: object
      properties:
        code:
          type: string
          example: DUPLICATE_ENTRY
        statusCode:
          type: number
          example: 409
        message:
          type: string
          example: Duplicate entry detected [ Email, Porovider = LOCAL ]
        sql:
          type: string
          example: "CALL spUserSignUpLocal('mapsea@mapseacorp.com', 'mapsea', '01012341234', '서울특별시 관악구 호암로24길 6 서울대 캠퍼스타운 창업 HERE-RO 5', '4층 401, 402호', '2024-08-21 14:31:10.278', '127.0.0.1', '2023-08-21 14:31:10.278', '$2b$10$gfCC9yA8WQsLBBIHjnI3yOnZoxqDNYD6wzhlSzDwKd4HVTEDWLCIq', 'Y', 'Y', 'Y', 'Y', 'Y', 'LOCAL', 'SERVICE_01', '2023-08-21 14:31:10.278');"
    # 데이터 유효성 에러가 발생한 경우
    ValidationError:
      type: object
      properties:
        code:
          type: string
          example: AUTH_FORBIDDEN
        statusCode:
          type: number
          example: 422
        message:
          type: string
          example: Validation fail, entered data is incorrect.
        Validation:
          type: object
          properties:
            b_no[0]:
              type: object
              properties:
                location:
                  type: string
                  default: "body"
                value:
                  type: string
                  default: "12345678901"
                msg:
                  type: string
                  default: "Invalid value"

    ##########################################################################################
    ##################                    Http Status 5XX                   ##################
    ##########################################################################################
    # 서버 자체측에서 문제가 발생한 경우
    InternalError:
      type: object
      properties:
        code:
          type: string
          example: INTERNAL_ERROR
        statusCode:
          type: number
          example: 500
        message:
          type: string
          example: Internal Server Error
